# Generated by Django 5.2.7 on 2025-11-07 20:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=421, null=True, unique=True)),
                ('category_name', models.CharField(choices=[('power_tools', 'Power Tools'), ('hand_tools', 'Hand Tools'), ('fasteners', 'Fasteners & Fixings'), ('electrical', 'Electrical Components'), ('plumbing', 'Plumbing & Piping'), ('building_materials', 'Building Materials'), ('adhesives', 'Adhesives & Sealants'), ('paints', 'Paints & Finishes'), ('safety_ppe', 'Safety Equipment & PPE'), ('fittings', 'Hardware Fittings'), ('abrasives', 'Abrasives & Consumables'), ('hvac', 'HVAC & Ventilation'), ('garden', 'Garden & Outdoor'), ('storage', 'Storage & Organization'), ('machinery', 'Machinery & Equipment')], default='paints', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('warrenty', models.DateField(blank=True, help_text='Warrenty Expire Date, if available', null=True)),
                ('default_unit_of_measure', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=5)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilize_no', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
                ('items', models.ManyToManyField(blank=True, related_name='issue_items', to='inventory.item')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
