# Generated by Django 5.2.7 on 2025-11-09 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
    ]
