# Generated by Django 5.2.7 on 2025-11-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=421, null=True, unique=True),
        ),
    ]
