# Generated by Django 5.2.7 on 2025-11-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='unit_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
