# Generated by Django 5.2.7 on 2025-11-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_purchase_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
